export default {
  token: localStorage.getItem('auth-token') || '',
  isLoading: false,
  name: '',
  role: '',
  customer: {},
  recs: [],
  title: 'Customers Infomation',
  icon: 'people',
  selected: [],
  isModalOpened: false,
  editingRec: {},
  backupRec: {},
  currentScannedGiftCardCode: '',
  qrCodePaymentId: 'xxx',
  cols: [
    {
      name: 'edit',
      align: 'left',
      field: 'edit',
      width: '34px',
    },
    {
      name: 'name',
      label: 'Name',
      align: 'left',
      field: 'name',
      sortable: true,
    },
    {
      name: 'username',
      label: 'User Name',
      align: 'left',
      field: 'username',
      sortable: true,
    },
    {
      name: 'address',
      label: 'Address',
      align: 'left',
      field: 'address',
      sortable: true,
    },
    {
      name: 'phone',
      label: 'Phone',
      align: 'left',
      field: 'phone',
      sortable: true,
    },
    {
      name: 'balance',
      label: 'Balance',
      align: 'left',
      field: 'balance',
      sortable: true,
    },
    {
      name: 'points',
      label: 'Points',
      align: 'left',
      field: 'points',
      sortable: true,
    },
  ],
  fields: [
    {
      name: 'id',
      hidden: true,
    },
    {
      name: 'name',
      label: 'Name',
      type: 'text',
      icon: 'person',
    },
    {
      name: 'username',
      label: 'User Name',
      type: 'text',
      icon: 'account_box',
    },
    {
      name: 'password',
      label: 'PassWord',
      type: 'text',
      icon: 'vpn_key',
    },
    {
      name: 'address',
      label: 'Address',
      type: 'text',
      icon: 'person_pin_circle',
    },
    {
      name: 'phone',
      label: 'Phone',
      type: 'text',
      icon: 'contact_phone',
    },
    {
      name: 'balance',
      label: 'Balance',
      type: 'text',
      icon: 'account_balance_wallet',
    },
    {
      name: 'points',
      label: 'Points',
      type: 'text',
      icon: 'stars',
    },
  ],
}
