export default {
  recs: [],
  counter: 1,
  allMenus: [],
  editingRec: {},
  backupRec: {},
  selected: [],
  isModalOpened: false,
  isLoading: false,
  cols: [
    {
      name: 'edit',
      align: 'left',
      field: 'edit',
      width: '34px',
    },
    {
      name: 'name',
      label: 'Name',
      align: 'left',
      field: 'name',
      sortable: true,
    },
    {
      name: 'desc',
      label: 'Desc',
      align: 'left',
      field: 'desc',
      sortable: true,
    },
    {
      name: 'price',
      label: 'Price',
      align: 'left',
      field: 'price',
      sortable: true,
    },
    {
      name: 'img',
      label: 'Image',
      align: 'left',
      field: 'img',
      sortable: true,
    },
  ],
}
