export default {
  isModalOpened: false,
  isModalQRCodeOpened: false,
  isModalPrintOpened: false,
  currentGenGiftCardCode: 'xxx',
  isLoading: false,
  name: 'Gift Card',
  recs: [],
  title: 'Gift Card',
  icon: 'card_giftcard',
  selected: [],
  cols: [
    {
      name: 'qrcode',
      align: 'left',
      field: 'id',
      width: '34px',
    },
    {
      name: 'userName',
      label: 'User Name',
      align: 'left',
      field: 'userName',
      sortable: true,
    },
    {
      name: 'amount',
      label: 'Amount',
      align: 'left',
      field: 'amount',
      sortable: true,
    },
    {
      name: 'expiry',
      label: 'Expiry',
      align: 'left',
      field: 'expiry',
      sortable: true,
    },
    {
      name: 'createdAt',
      label: 'Create Date',
      align: 'left',
      field: 'createdAt',
      sortable: true,
      format: val => `${new Date(val).toLocaleString('en-US')}`,
    },
  ],
}
